discourse_openid_connect:
  openid_connect_enabled:
    default: false
  openid_connect_discovery_document:
    default: ""
  openid_connect_client_id:
    default: ""
  openid_connect_client_secret:
    default: ""
    secret: true
  openid_connect_rp_initiated_logout:
    default: false
  openid_connect_rp_initiated_logout_redirect:
    default: ""
  openid_connect_allow_association_change:
    default: false
  openid_connect_overrides_email:
    default: false
  openid_connect_authorize_scope:
    default: "openid"
  openid_connect_verbose_logging:
    default: false
  openid_connect_token_scope:
    default: ""
  openid_connect_error_redirects:
    default: ""
    type: list
    list_type: secret
  openid_connect_authorize_parameters:
    default: ""
    type: list
    list_type: compact
  openid_connect_claims:
    default: ""
    textarea: true
  openid_connect_match_by_email:
    default: true
  openid_connect_use_pkce:
    default: false
  openid_connect_verbose_log:
    default: false
  openid_connect_validate_email:
    default: true
  openid_connect_groups_enabled:
    default: false
    client: true
  openid_connect_groups_mapping:
    default: ""
    type: list
    list_type: simple
  openid_connect_groups_remove_unmapped_groups:
    default: true
  openid_connect_gitlab_override_if_user_exists:
    default: true
  openid_connect_gitlab_api_base:
    default: ""
  openid_connect_gitlab_api_private_token:
    default: ""
    type: secret
  opendid_connect_groups_gitlab_repository_role_mapping:
    default: ""
    type: list
    list_type: simple
  opendid_connect_gitlab_remove_unmapped:
    default: true
  openid_connect_gitlab_api_verbose_log:
    default: false
